### ISSUE TITLE
[GrimAC] Global task for GrimAC v2.3.40 generated an exception java.lang.UnsupportedOperationException: null

### ISSUE THREAD

**Issue by SaltyAlpha** [SaltyAlpha/Grim#1026]
> [!NOTE]
> Imported issue from `GrimAnticheat/Grim#1026`.
> Original author: `AVuTuVA`; created: `2023-04-08T15:51:48Z`; updated: `2024-05-31T09:47:05Z`.
> Original state: `closed`; assignees: none; milestone: none.
> Original URL: `https://github.com/GrimAnticheat/Grim/issues/1026`.

### Stack trace

[16:17:26 WARN]: [GrimAC] Global task for GrimAC v2.3.40 generated an exception
java.lang.UnsupportedOperationException: null
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.handle(CraftScheduler.java:536) ~[folia-1.19.4.jar:git-Folia-"043f070"]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:236) ~[folia-1.19.4.jar:git-Folia-"043f070"]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:212) ~[folia-1.19.4.jar:git-Folia-"043f070"]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:176) ~[folia-1.19.4.jar:git-Folia-"043f070"]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.runTask(CraftScheduler.java:145) ~[folia-1.19.4.jar:git-Folia-"043f070"]
        at ac.grim.grimac.utils.lists.CorrectingPlayerInventoryStorage.checkThatBukkitIsSynced(CorrectingPlayerInventoryStorage.java:108) ~[grimac-2.3.40.jar:?]
        at ac.grim.grimac.utils.lists.CorrectingPlayerInventoryStorage.tickWithBukkit(CorrectingPlayerInventoryStorage.java:123) ~[grimac-2.3.40.jar:?]
        at ac.grim.grimac.manager.tick.impl.TickInventory.tick(TickInventory.java:11) ~[grimac-2.3.40.jar:?]
        at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.1-jre.jar:?]
        at ac.grim.grimac.manager.TickManager.tickAsync(TickManager.java:34) ~[grimac-2.3.40.jar:?]
        at ac.grim.grimac.manager.init.start.TickRunner.lambda$start$0(TickRunner.java:17) ~[grimac-2.3.40.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:178) ~[folia-1.19.4.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:36) ~[folia-1.19.4.jar:?]
        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:194) ~[folia-1.19.4.jar:git-Folia-"043f070"]
        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:149) ~[folia-1.19.4.jar:git-Folia-"043f070"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[folia-1.19.4.jar:git-Folia-"043f070"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.19.4.jar:git-Folia-"043f070"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Grim version

v2.3.40

### Server version

Folia-last

### Plugins

Grim

**Comment by SaltyAlpha** [comment]
## Imported discussion

> Original conversation comment by `MWHunter` at `2023-04-08T17:52:48Z`.

oops, forgot to use the folia scheduler for that file

---

> Original conversation comment by `ghost` at `2023-04-10T10:12:03Z`.

@​AVuTuVA привет

---

> Original conversation comment by `SamB440` at `2024-05-31T09:47:05Z`.

This seems to be using the folia scheduler now.

---
